[package]
name = "rusty-life-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.99"
rusty-life-lib = { path = "../rusty-life-lib" }
getrandom = { version = "0.2", features = ["js"] }

[lib]
crate-type = ["cdylib"]